### ISSUE TITLE
When tidying all tabs, sometimes dashboard doesn't open

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#64]
I couldn't catch the exact scenario to reproduce. Sometimes dashboard doesn't open as a pinned tab and Chrome closes completely.

Chrome 58.0.3029.81 (64-bit)
TidyTab v2.7.0
Windows 10 Pro

**Comment by briangonzalez** [comment]
I have noticed this as well. In fact, we have some code which explicitly targets windows to try to solve for some of it's shortcomings.

https://github.com/eggplanetio/tidytab/blob/master/app/component/popup.vue#L111

I think the issue is caused by the fact that the close-and-open-dashboard code lives within the pop up, and if the the pop up is dismissed prematurely, no further code is executed.

I am going to look into using the background process to perform the closing and opening of the dashboard to mitigate this issue.

**Comment by briangonzalez** [comment]
@erenseymen Mind giving this release a shot? Thanks!

https://github.com/eggplanetio/tidytab/releases/tag/2.9.0
